version: '2.1'
orbs:
  codecov: codecov/codecov@4.1.0
jobs:
  test-and-upload-python:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest --cov .
      - codecov/upload
workflows:
  upload-to-codecov:
    jobs:
      - test-and-upload-python
